# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7683c940b72419bc5df406f0f06ce2177d77c90bb021445d41a279e5b2a9adada5f349fa4a565c51c5f1367d1a7e582f222e95d091a2902a269214f8d55af1aa

test:
  secret_key_base: 904b8b690d13a417a574141be46dd3c290b1368788c791ac116019dabf80c8491a58a1c4e9e6a893d980e62e2d21f160205e617f3fe23ce93f81fd0706d62d44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
